export const routes = {
  portals: {
    master: "/master",
    seller: "/seller",
    customer: "/login",
  },
  auth: {
    login: "/login",
    masterLogin: "/master",
    sellerLogin: "/seller",
    otpLogin: "/auth/otp-login",
    pinLogin: "/auth/pin-login",
    forgotPassword: "/auth/forgot-password",
  },
  superAdmin: {
    dashboard: "/master/dashboard",
    users: "/master/users",
    shopOwners: "/master/shop-owners",
    shopOwnerDetails: (id: string | number) => `/master/shop-owners/${id}`,
    shopOwnerEdit: (id: string | number) => `/master/shop-owners/${id}/edit`,
    shops: "/master/shops",
    categories: "/master/categories",
    brands: "/master/brands",
    subCategories: "/master/sub-categories",
    productTypes: "/master/product-types",
    models: "/master/models",
    productAttributes: "/master/product-attributes",
    productCompatibilities: "/master/product-compatibilities",
    products: "/master/products",
    productApprovals: "/master/product-approvals",
    reports: "/master/reports",
    notifications: "/master/notifications",
    settings: "/master/settings",
  },
  shopOwner: {
    dashboard: "/seller/dashboard",
    shops: "/seller/shops",
    staff: "/seller/staff",
    vendors: "/seller/vendors",
    products: "/seller/products",
    shopProducts: "/seller/shop-products",
    purchases: "/seller/purchases",
    purchaseReturns: "/seller/purchase-returns",
    sales: "/seller/sales",
    salesReturns: "/seller/sales-returns",
    stockTransfers: "/seller/stock-transfers",
    physicalStock: "/seller/physical-stock",
    barcode: "/seller/barcode",
    expenses: "/seller/expenses",
    orders: "/seller/orders",
    invoices: "/seller/invoices",
    customers: "/seller/customers",
    reports: "/seller/reports",
    notifications: "/seller/notifications",
    settings: "/seller/settings",
  },
  shopStaff: {
    dashboard: "/shop-staff/dashboard",
    pos: "/shop-staff/pos",
    sales: "/shop-staff/sales",
    salesReturns: "/shop-staff/sales-returns",
    stock: "/shop-staff/stock",
    stockTransfers: "/shop-staff/stock-transfers",
    physicalStock: "/shop-staff/physical-stock",
    customers: "/shop-staff/customers",
    barcode: "/shop-staff/barcode",
    notifications: "/shop-staff/notifications",
  },
  customer: {
    home: "/customer/home",
    products: "/customer/products",
    productDetails: (id: string | number) => `/customer/products/${id}`,
    cart: "/customer/cart",
    checkout: "/customer/checkout",
    orders: "/customer/orders",
    orderDetails: (id: string | number) => `/customer/orders/${id}`,
    invoices: "/customer/invoices",
    wishlist: "/customer/wishlist",
    reviews: "/customer/reviews",
    profile: "/customer/profile",
    notifications: "/customer/notifications",
  },
  vendor: {
    dashboard: "/vendor/dashboard",
    profile: "/vendor/profile",
    purchaseOrders: "/vendor/purchase-orders",
    payments: "/vendor/payments",
    productsSupplied: "/vendor/products-supplied",
    reports: "/vendor/reports",
    notifications: "/vendor/notifications",
  },
};
